### PR TITLE
Raft options

### PR DESCRIPTION
**Pull request by yourcodesucks**
- Updated geth, constellation-node binaries to latest stable for mac platform
- Added bootnode to account for new key creation mechanism
- Made several changes to commandline creation for new version of the related binaries
- Updated key creation process for new version of the related binaries
- Started adding Raft configuration
- Expanded error reporting
- Updated isUnlocked work-around error condition
- Geth RPC request errors now include request information in the log
- Prefixed some numeric geth api parameters with 0x

### CODE REVIEW

**Comment by Ajaysethi136** [comment]
@yourcodesucks Can we incorporate your changes into the current version of cakeshop for RAFT compatibility, Does it work with RAFT?

Regards,
Ajay

**Comment by Ajaysethi136** [comment]
@yourcodesucks thanks a lot.

But i'm not able to make out anything from the files which you shared.

As you mentioned, cakeshop works fine with Raft, could you please cakeshop repo with your changes, will build a jar out of that and run that.

**Comment by yourcodesucks** [comment]
I can't merge into the official repo. You can clone mine and build it. then take cakeshop-0.10.0.war from cakeshop-api/target/ and copy it into each of the three node folders. After that in three separate cli windows start cakeshop as follows: `java -jar cakeshop-0.10.0.war`. Keep in mind that the web UI is still busted, but you can attach with geth as `./geth attach /Users/mike/Projects/cakeshop.git/0/data/local/ethereum/geth.ipc` from any of the data/geth/quorum/mac directories.

**Comment by Ajaysethi136** [comment]
@yourcodesucks  Yes, Can you please send me your repo, I don't have your repo.

These are steps to run cakeshop:
Will build a jar out of your code.
java -jar cakeshop.war example and then will set the value of geth.url and rpc port
then, it should work on localhost:8080
Is this correct??

**Comment by yourcodesucks** [comment]
you can do this to get my code`git clone -b quorum-ui --single-branch https://github.com/yourcodesucks/cakeshop.git`. if you `cd` into the `data/geth/quorum/mac` directory of the 0 folder in a 4th commandline window, you can run geth attach command after starting cakeshop war in that same directory in a different commandline window.

the url is correct, but the web UI doesn't presently function. that is not related to my raft changes, but i was planning on looking at that since raft adds parameters that will need to be added to the UI as well.

**Comment by Ajaysethi136** [comment]
@yourcodesucks thanks. I got the code. but as you said, UI is busted then how will we monitor the Quorum node data(Blocks Data) on the UI?

Can we connect via mail (my emailid: ajaysethi136@gmail.com) if possible

**Comment by cvkonduru** [comment]
@Ajaysethi136 @fixanoid  Does CakeShop work with Quorum 2.0.2 using Istanbul BFT?

**Pull request merged**
